# Generated by Django 5.1.7 on 2025-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_student_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_count',
            field=models.IntegerField(default=0),
        ),
    ]
